services:
  app:
    build:
      context: ./identity-provider   # Spécifie le répertoire où se trouve Dockerfile
      dockerfile: Dockerfile         # Nom du Dockerfile (optionnel si c'est "Dockerfile")
    container_name: node_app
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=postgres
      - DB_USER=postgres
      - DB_PASS=postgres_password
      - DB_NAME=identity_db
      - JWT_SECRET=your_jwt_secret
    depends_on:
      - postgres

  cryptomonnaie:
    build:
      context: ./Cryptomonnaie       # Répertoire contenant Dockerfile pour Crypto
      dockerfile: Dockerfile         # Dockerfile du projet Crypto
    container_name: cryptomonnaie_app
    ports:
      - "5000:80"    # Pour accéder au projet ASP.NET MVC via HTTP
      - "5001:443"   # Pour accéder au projet ASP.NET MVC via HTTPS
    environment:
      - ConnectionStrings__DefaultConnection=Server=postgres;Database=cryptomonnaie_db;User=postgres;Password=postgres_password;
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_DB: identity_db
    ports:
      - "5433:5432"  # Utilise le port 5433 local pour éviter les conflits
    volumes:
      - data_protection_keys:/root/.aspnet/DataProtection-Keys
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d

volumes:
  postgres_data:
  data_protection_keys:
