-- Supprimer les tables
DROP TABLE IF EXISTS Token CASCADE;
DROP TABLE IF EXISTS Tokens CASCADE;
DROP TABLE IF EXISTS Session CASCADE;
DROP TABLE IF EXISTS Connexion CASCADE;
DROP TABLE IF EXISTS CodePin CASCADE;
DROP TABLE IF EXISTS ModifUtilisateur CASCADE;
DROP TABLE IF EXISTS LimiteConnexion CASCADE;
DROP TABLE IF EXISTS DureeSession CASCADE;
DROP TABLE IF EXISTS Utilisateur CASCADE;